### ISSUE TITLE
Custom Distribution URL pattern & Authentication

### ISSUE THREAD

**Issue by napstr** [siouan/frontend-gradle-plugin#108]
Hi,

I'd love to see some advanced customization for the download URL and request like authentication.
The `ResolveYarnDistributionUrl` already uses a pattern to fill in the version...maybe it would be possible to allow the user to provide that pattern instead of currently only a hardcoded url?

Also being able to authenticate the requests would be great.

**Target environment**
 
- OS: any
- JDK: any
- Gradle: any

Settings in `build.gradle[.kts]` file:
```groovy
frontend {
    nodeVersion = '12.6.1'
    nodeDistributionUrlPattern = 'https://foo.org/bar/node/vVERSION/node-vVERSION-OS_EXTENSION'
    distributionRequestAuthorization = "$user:$pass".bytes.encodeBase64().toString()
}
```

**Comment by napstr** [comment]
I'm working on a PR for this to demonstrate the ideas more concretely.

**Comment by v1nc3n4** [comment]
Hi @napstr,
Thank you for your message, and these interesting proposals!

**URL pattern**
Actually, I'm not sure about the use case with the URL pattern you're introducing. Now, my understanding is it would allow hosting multiple distributions on a server with a custom layout: people would define a URL pattern to browse into this directory layout.
- Is it right?
- Do you have such need actually?

**Server authentication**
Actually, 3 features are already in the roadmap, but not visible in issues yet, and related more or less to your proposal:
- Authentication on the server providing Node.js distributions.
- Authentication on the server providing Yarn distributions.
- Authentication on the proxy server.
All 3 authentications would support BASIC access only. I will create one feature request for each point, to allow focusing on simple use cases and cut complexity.

BR,
Vincent

**Comment by napstr** [comment]
> **URL pattern**
> Do you have such need actually?

Currently, the only alternative when wanting to download from a custom url (for example, hosting via JFrog Artifactory) is hardcoding the full url with `nodeDistributionUrl`/`yarnDistributionUrl` including version and operation system. But then one misses out on one of the great features of this plugin, which is automatic detection of the operating system.

What you wrote about the authentication sounds exactly correct.

**Comment by napstr** [comment]
Check out #109 for a first idea to implement these things.

**Comment by v1nc3n4** [comment]
@napstr,
FYI, regarding the Node.js distribution URL pattern, using the pattern makes now the former `nodeDistributionUrl` property unrelevant. To be consistent with semantic versioning and help end-users guess the content of each release, this feature will be delivered with a major release 3.x, because it introduces a breaking change.

Then, I will create dedicated issues for authentication-related features, that will be delivered with minor releases 2.x.

**Comment by napstr** [comment]
👍 I think consolidating the interface of the plugin is a very good idea.
Why not consider delivering the feature in 2.x, while at the same time deprecating the `nodeDistributionUrl`, and removing it once 3.0 is ready?

**Comment by v1nc3n4** [comment]
Yes, I agree with the principle. I see these drawbacks though:
- Temporary living with two syntaxes may lead to confused ideas with end-users, even if documentation states clearly what happens if both properties are used together.
- A specific implementation would be necessary to handle this temporary situation, with the risk to introduce a bug.

However, my previous comment was a bit hasty, all features can be delivered together in a single major release, I don't see actually the need to create an intermediate minor release 2.x. Sorry for that!

**Comment by trohr** [comment]
Hello, is it possible to just specify a root URL for mirror of the Node / NPM distributions?

The use case is simple: we would like to make only a mirror of the official repositories on our company servers (lazy mirror that would download packages and files as clients would request them). In this case, the structure is identical to the main Node distribution / NPM packages.

How can we achieve that using your plugin?

Is there a way to specify only 'nodeDistributionRoot' / 'npmDistributionRoot' URLs like in the moowork plugin?
e.g.: 
```
  // Base URL for fetching node distributions (change if you have a mirror).
  distBaseUrl = 'https://nodejs.org/dist'
```

Thank you for your comments.
Tomas Rohrbacher

**Comment by v1nc3n4** [comment]
Hi Tomas,
Thank you for your message.
The feature requested by @napstr in this discussion allows to deal with your use case. The syntax is a bit different than the one used by the moowork plugin. Typically, to mirror the official Node.js distribution URLs with your company's server, you would configure the plugin this way:

```groovy
nodeDistributionUrlPattern = 'https://yourcompany.org/dist/vVERSION/node-vVERSION-ARCH.TYPE'
```

The `nodeDistributionUrlPattern` property replaces the former `nodeDistributionUrl` property available in releases 2.x. Tokens with uppercase are automatically resolved by the plugin, using the `nodeVersion` property and the current platform architecture. This feature is now implemented, and is planned in release 3.0. It shall be delivered mid-May.
You will find the documentation for release 3.0 [here](https://github.com/siouan/frontend-gradle-plugin/tree/3.0#dsl-reference).

Let me know if it sounds good to you!
BR,
Vincent

**Comment by trohr** [comment]
> Hi Tomas,
> Thank you for your message.
> The feature requested by @napstr in this discussion allows to deal with your use case. The syntax is a bit different than the one used by the moowork plugin. Typically, to mirror the official Node.js distribution URLs with your company's server, you would configure the plugin this way:
> 
> ```groovy
> nodeDistributionUrlPattern = 'https://yourcompany.org/dist/vVERSION/node-vVERSION-ARCH.TYPE'
> ```
> 
> The `nodeDistributionUrlPattern` property replaces the former `nodeDistributionUrl` property available in releases 2.x. Tokens with uppercase are automatically resolved by the plugin, using the `nodeVersion` property and the current platform architecture. This feature is now implemented, and is planned in release 3.0. It shall be delivered mid-May.
> You will find the documentation for release 3.0 [here](https://github.com/siouan/frontend-gradle-plugin/tree/3.0#dsl-reference).
> 
> Let me know if it sounds good for you!
> BR,
> Vincent

Hello Vincent.

The solution you and @napstr propose certainly is reasonable.

First, let me explain my background so that you can assess whether my point of view is relevant.
- I am not a Node/JS developer and I don't know about specifics of using node/yarn in that I cannot assess properly whether specifying VERSION, ARCH and other placeholders in the URL pattern is required.
- I am a backend senior developer / devops engineer and I am interested in getting the frontend build to build nicely within our environment.

From my point of view, it would be better to split the nodeDistributionUrlPattern into 2 properties.
Let me explain:

- URL to the root of the node / npm / yarn distribution is something that would like to configure as system environment properties that will be supplied to the build (because root url of our distribution mirrors host may change in the future and we don't want to rewrite every build.gradle file if that happens). 
- However structure of the internal path within the distribution root is dictated how Node / Yarn / NPM decides to structure their repositories. I think it is of no concern to us. Logic on how to create path to concrete distribution thus should be provided by your plugin with default value (with feature to be configurable; this feature will not be used by us).

If you find my arguments valid, than these is configuration that I propose:
`{
  frontend {
    nodeVersion = '12.6.1'
    nodeDistributionUrlRoot = 'https://nodejs.org/dist/'
    nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-OS_EXTENSION'
    nodeDistributionRequestAuthorization = "$user:$pass".bytes.encodeBase64().toString()

    yarnVersion = '1.22.4'
    yarnDistributionUrlRoot = 'https://github.com/yarnpkg/yarn/releases/download/'
    yarnDistributionUrlPathPattern = "vVERSION/yarn-vVERSION.tar.gz"
    yarnDistributionRequestAuthorization = "$user:$pass".bytes.encodeBase64().toString()
}
}`

We shall be using it like that:
gradle.properties:
`node.distributionUrlRoot=https://server.company.com:8181/artifactory/node-distribution/
yarn.distributionUrlRoot=https://server.company.com:8181/artifactory/yarn-releases/
`

build.gradle:
`{
  frontend {
    nodeVersion = '12.6.1'
    nodeDistributionUrlRoot = "${node.distributionUrlRoot}"
    nodeDistributionRequestAuthorization = "$repositoryLogin:$repositoryPassword".bytes.encodeBase64().toString()

    yarnVersion = '1.22.4'
    yarnDistributionUrlRoot = "${node.distributionUrlRoot}"
    yarnDistributionRequestAuthorization = "$repositoryLogin:$repositoryPassword".bytes.encodeBase64().toString()
}
}`

For me, package-layout scheme is not important and I would like to evade increased complexity of setting it up throughout our entire build process.

Or is the internal package-layout structure of Node/Yarn important in some way so that we should be concerned about it?

**Comment by v1nc3n4** [comment]
Hi Tomas,
Thank you for introducing the context.

- Your arguments absolutely make sense for me, and the URL pattern will be splitted in two properties for both Node.js/Yarn: `xxxxDistributionUrlRoot` and `xxxxDistributionUrlPathPattern`.
- Regarding authentication on both distribution and proxy servers, configuration is already splitted in [2 properties](https://github.com/siouan/frontend-gradle-plugin/tree/3.0#table-of-properties). Authentication scheme itself is not configurable because actually 'Basic' is the only scheme supported (supporting other schemes would require a specific implementation).

Implementation for URL patterns of Node.js and Yarn distributions will be updated for release 3.
BR,
Vincent

**Comment by trohr** [comment]
Thank you.

Please, can I try the 3.0.0-SNAPSHOT version of the plugin somehow?

I tried reading the docs, but there is no information about using development version of the plugin in CONTRIBUTING.md; also, the plugins portal sais that version 2.0.0 is latest.
Or should I build the development version on localhost and use this version?

Thank you.
Tomas Rohrbacher

**Comment by v1nc3n4** [comment]
- Plugins portal: publishing release `2.1.0` two weeks ago failed partially Gradle' side, I don't know why. And, unfortunately, the portal does not handle publish requests atomically, and there's no way to force re-publishing a release. The release was effectively published, artifacts are available, but the portal does not show it on the plugin's page. An [issue](https://github.com/gradle/plugin-portal-requests/issues/40) is opened at Gradle's, but still I'm waiting for a feedback 😞.
- Actually snapshots are not published. If you want to try a snapshot of branch 3.0, here's how to do:
  - Clone the repository with Git and checkout branch `3.0`.
  - Execute `./gradlew build publishToMavenLocal` in the root directory.

A snapshot will be published in the Maven local repository, and can be used like any other regular release on the same workstation. Take care to remove the published artifacts in the local repository once release `3.0.0` is officially published.
Vincent

**Comment by trohr** [comment]
Hello, I have subsequent question:

- distributions of yarn and npm are now able to be downloaded from different URLs,
- but what about the npm packages as dependencies from package.json themselves? is there option to configure a mirror/proxy as well?

Thank you,
Tomas Rohrbacher

**Comment by napstr** [comment]
I believe that can be achieved outside of this plugin, for npm see https://docs.npmjs.com/configuring-your-registry-settings-as-an-npm-enterprise-user
Yarn works similarly, afaik both npm and yarn will save the registry URL to the lock file, so the packages will be downloaded from the private registry when installing.

Developers on their work machines can configure the login to the private registry in their home directory. The trickiest part here in my experience is automating the login to the private registry on the CI.

**Comment by v1nc3n4** [comment]
Hi Tomas!
Indeed, as mentioned by @napstr, both npm and Yarn have their own proxy settings. The plugin is not intended to replace/create a shortcut of these settings. The proxy feature in the plugin is dedicated for its own features, i.e. download distributions.
BR,
Vincent
