### ISSUE TITLE
[Question] Need help using the multi-projects war example

### ISSUE THREAD

**Issue by eancuta** [siouan/frontend-gradle-plugin#151]
Hi,

I am trying to use your example project to set up a Spring Boot service with a Vue.js front-end.

Unfortunately I cannot find any documentation on how to configure the front-end folder. I have added vue to the package.json file, but I don't know which script to change or how to change the config.js file to properly start it.

I would appreciate some help if that's okay.

**Comment by v1nc3n4** [comment]
Hello,

> how to configure the front-end folder. [...] I don't know which script to change or how to change the config.js file [...]

I'm not sure what you mean by that.

The plugin acts as a bridge between Gradle and NPM/Yarn projects. It allows to integrate the build of such project (e.g. a frontend SPA) in a build executed by Gradle (e.g. the build of a full-stack webapp). The plugin does not suggest/force any organisation or layout of your frontend project. The only things the plugin require generally are:
- A Node.js distribution.
- A Yarn distribution (if your are using Yarn instead of NPM).
- A `package.json` file describing the tasks to build your frontend project.

The `scripts` section in the `package.json` file is generally used to build the frontend project with NPM/Yarn. If you have set up a Vue.js project with Vue CLI, you should have something like that in your `package.json` file:

```package.json
...
"scripts": {
    "build": "vue-cli-service build",
    "start": "vue-cli-service serve",
    "test": "vue-cli-service test:unit",
}
...
```

The `build` script allows to build the frontend project so as it can be deployed afterwards. If you are using another tool to init your frontend project, the content of the `scripts` section will be different, but the philosophy is generally the same. Finally, when you want to integrate the build in Gradle, you would configure the plugin's `assembleScript` property with `run build`.

In the examples, we can't make any assumption about which frontend lib or framework you use (Vue.js, Nuxt, React, Angular, etc). That's why a simple JS file `config.js` is used to build the project and demonstrate that you can trigger whatever you want as long as it is something runnable with `node`, `npm`, or `yarn` executables. You should simply replace the `package.json` file in the example with yours, and remove the `config.js` file of course.

If you want to see a live example of building a frontend project with Gradle and the plugin, you could also take a look at the plugin's [website project](https://github.com/siouan/frontend-gradle-plugin/tree/master/site), which is a Nuxt (Vue.js) frontend application.

It that clear? Do you need more information?

**Comment by eancuta** [comment]
Hi v1nc3n4,

That is very helpful, thank you. It is exactly what I was looking for.

In the sample project, I changed the "build" script from `
    "build": "echo Building frontend && mkdirp build/www && node config/config.js",` to `
    "build": "echo Building frontend && vue-cli-service build",`
    
Now I am getting what I expected and the trigger of gradle build now does a vue build on the frontend project.

The only issue I have at the moment is that build.gradle in the backend section from the example references the build directory as `def frontendBuildDir = file("${project(':frontend').buildDir}/www")`, but I don't know how to set the `${project(':frontend').buildDir}` to become dist instead of build

**Comment by v1nc3n4** [comment]
You must not try to change `${project(':frontend').buildDir}` which is a way to tell Gradle to look in the frontend project root directory. If I understand well what you are trying to do, the important part for you is to change the `www` directory with the relevant one, i.e. generally the `dist` directory.

Hope this helps...

**Comment by v1nc3n4** [comment]
Sorry, I was mistaken: you should replace the whole line with: `def frontendBuildDir = file("${project(':frontend')}/dist")`

**Comment by eancuta** [comment]
Ok, I actually ended up defining buildDir in the build.gradle file for the frontend and then removing the /www from the original sentence.

Thank you so much for the assist. I now understand the purpose of this project a bit more and I really appreciate the help even though my question wasn't really related to your plugin.

I have a question about the `def frontendResourcesDir = file("${project.buildDir}/resources/main/public")`. Am I correct in assuming this has nothing to do with copying resources from the Java backend /src/main/resources? As far as I can tell this frontendResourcesDir just points to where everything should be compiled into in the build directory.

I will close this question once you reply and I thank you again

**Comment by v1nc3n4** [comment]
To understand the `frontendResourcesDir` property, it is important to understand how Spring Boot assembles the final WAR/JAR artefact and [deals with static resources](https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot) (e.g. a frontend application). By default, Spring Boot peeks artefacts located in the `src/main/resources/public` directory (among others), and make them accessible at the root of your web application. Generally, we put in this directory static resources (e.g. HTML pages, JS scripts, CSS stylesheets, etc).

So if you want your frontend project to be publicly served by your Spring Boot backend project, the frontend artefacts built in the `${project(':frontend')}/dist` directory must be copied in the `${project(':backend').buildDir}/src/main/resources/public` directory before Spring Boot assembles the WAR/JAR artefact.
If you decide to copy frontend artefacts directly in the `${project(':backend')}/src/main/resources/public` directory of your backend project, it should work, because this directory is copied in the `buildDir` directory later. But you may face problems with VCS, and you may have to exclude this content. I don't think it's a good way to do that.

FYI, I will update the example to use the `dist` directory, avoid confusion with Gradle `build` directory, and make things clearer.
