### ISSUE TITLE
Gradle clean runs install

### ISSUE THREAD

**Issue by tschmidt01** [siouan/frontend-gradle-plugin#162]
When running `gradle clean` in the provided `multi-projects-war-application` example, the plugin will invoke the `install` script before cleaning:

```
~/Desktop/frontend-gradle-plugin/examples/multi-projects-war-application(master*) » gradle clean
Picked up _JAVA_OPTIONS: -Xverify:none

> Task :frontend:installFrontend
npm WARN multi-projects-example@1.0.0 No description
npm WARN multi-projects-example@1.0.0 No repository field.
npm WARN multi-projects-example@1.0.0 No license field.

audited 1 package in 0.871s
found 0 vulnerabilities


> Task :frontend:cleanFrontend

> multi-projects-example@1.0.0 clean /Users/sm/Desktop/frontend-gradle-plugin/examples/multi-projects-war-application/frontend
> echo Cleaning frontend

Cleaning frontend

BUILD SUCCESSFUL in 3s
5 actionable tasks: 2 executed, 3 up-to-date
```

Is this intentionally or a bug?

**Comment by v1nc3n4** [comment]
Hi @tschmidt01,

Thank you for posting this question. This is indeed an intentional behaviour.
Cleaning the frontend project may not only be a matter of removing the `${buildDir}` directory of Gradle.
Depending on the project, it may be necessary to do additional actions, using npm or yarn, for instance if one builds an artifact outside the `${buildDir}` directory and wants to remove it. That's why frontend dependencies (generally dev dependencies) must be installed before, so as anyone can trigger a script defined in the `package.json` file during Gradle's `clean` task.

However, there's a place for optimization. As long as there are no `cleanScript` defined, there's no reason to invoke the `installFrontend` task.

I take the point and try to provide an improvement in the future. Thank you for your help.
Have a good week-end.
BR

**Comment by v1nc3n4** [comment]
Sorry, I was mistaken. The plugin already skips the `installFrontend` task if the `cleanScript` is not defined. So optimization is already done I think. The example tries to demonstrate multiple features by defining a `cleanScript`, but this property is not mandatory.

**Comment by tschmidt01** [comment]
Thanks a lot for the quick reply! I'm pretty new to Gradle, thus I've got another question: When building the `multi-projects-war-application` using `gradle build` multiple times without changing anything, I would expect that both `installFrontend` and `assambleFrontend` tasks won't get executed again because of Gradle's configuration cache. Is it intentionally that those tasks don't use the cached value but always get executed again?

**Comment by tschmidt01** [comment]
Got another question now: Is there any way to use Gradle's build cache for the install and assemble tasks? Like only doing a `npm install`, when the `package-lock.json` has changed? Same for assemble, if there is no modification in the sources, there is no reason to run the build again.

**Comment by v1nc3n4** [comment]
This is not as simple as it seems to be. For example, npm does not rely on the `package.json` file only. Moreover, both npm and yarn already provide optimizations to skip dependencies installation/update when it is not required.

As explained in the documentation of the [installFrontend](https://siouan.github.io/frontend-gradle-plugin/node-npm-npx-yarn-tasks#installFrontend) task, of the [assembleFrontend](https://siouan.github.io/frontend-gradle-plugin/node-npm-npx-yarn-tasks#assembleFrontend) task, and in this [comment](https://github.com/siouan/frontend-gradle-plugin/issues/151#issuecomment-785067267), the plugin does not attempt to duplicate logic and optimizations already implemented in both tools, because it will never perform as well, and it will increase drastically maintenance costs just to keep implementation synchronized with both tools. 

If you want to skip a task in your project, you can easily override its inputs/outputs using Gradle DSL, based on some basic [recommendations](https://siouan.github.io/frontend-gradle-plugin/node-npm-npx-yarn-tasks#tweaking-tasks).
Hope this helps!
BR

**Comment by v1nc3n4** [comment]
Hi,
I'm closing the issue due to inactivity. Feel free to open a new issue in case of problem.
BR
