### ISSUE TITLE
Spring+vue.js. Frontend not working after successfully done build tasks.

### ISSUE THREAD

**Issue by setofaces** [siouan/frontend-gradle-plugin#177]
Tried to make  (spring+vue.js) app using your plagin and following your way. Gradle builds my project without any issues, frontend tasks in particular too, API works fine, but there is no frontend at all, only vue,js favicon. Build outputs from frontend were successfully copied to backend/build/resources/main ( changed destination comparing to your example). 

Scripts section in package.json from frontend:
`
 

    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e",
    "lint": "vue-cli-service lint"
  ` 
Sorry, didnt manage to solve it myself  and dont have any experience of doing stuff like that, probably you have some. Thanks in advance.

**Comment by v1nc3n4** [comment]
Hello,

I'm sorry, I can't deal with the issue you are encountering because I don't see in the details you gave something that shows me the plugin is not working as expected.
That being said, the problem you are facing appears to be an integration issue between a JS webapp and a Spring Boot app, or a problem with the loading of the Vue.js app in your browser. So, if I were you:

- I would verify the functioning of the Vue.js app as a standalone app by running the `serve` script.
- I would then verify my Spring Boot app can serve static HTML resources. I guess it is already working because, if you see the favicon of your website in your browser, that means the HTML entrypoint (probably an `index.html` file) is correctly loaded in your browser when accessing to your webapp.
- Then, I would open the browser console and verify the Vue.js app did not log any error.

Hope this helps, good luck 🤞!
BR

**Comment by setofaces** [comment]
Thank you for such reply! The problem is  caused by incorrect paths to js scripts in index.html. They should be "static/js/..." but they are "/statics/js/...". I should make vue builder to create correct index.html in build folder. Thanks again!
