### ISSUE TITLE
Do not re-run the front-end build if the front end has no changed

### ISSUE THREAD

**Issue by FredericDesgreniers** [siouan/frontend-gradle-plugin#180]
Hi,

Currently the front-end build re-runs every time I make a build, even if the front-end hasn't changed. The task should let me declare all the input directories and use gradle caching to only re-run if an input has changed. If nothing has changed, the whole front-end build should just be skipped.

Not having this makes builds very slow and this plugin unusable for quick iteration. I have to disable the front-end project entirely during dev.

**Comment by v1nc3n4** [comment]
Hi @FredericDesgreniers,

Thank you for using this plugin and your question. There has been some discussions about this difficulty in the past.
The plugin cannot guess when it should or should not build the frontend artifacts, because this is entirely specific to each project. This is explained here: https://siouan.github.io/frontend-gradle-plugin/node-npm-npx-yarn-tasks#assembleFrontend

But, if you can provide a set of inputs and outputs relevant for any project - not only yours - the plugin may track to know if a rebuild is necessary, I would be very happy to read, because an improvement may be possible.

Gradle already provides out-of-the-box a mechanism to declare inputs and outputs of a task, aka "incremental build". This is described here: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

> The task should let me declare all the input directories and use gradle caching to only re-run if an input has changed.

Have you tried to declare your own inputs/outputs on the `assembleFrontend` task? If yes, what's the problem then?

If you see a generic solution, please share it with me because my answer is based on my actual knowledge, and I may be simply ignorant 😕.
BR

**Comment by FredericDesgreniers** [comment]
Oh declaring the inputs myself on assembleFrontend does exactly what I want it to do. Seems like it was my ignorance with gradle, didn't realize I could modify those tasks myself :)

Thanks for the prompt response, closing this

**Comment by v1nc3n4** [comment]
🎉 I'm very happy to read that!
On my side, I'm thinking about improving documentation, at least to explain how this can be handled with a concrete example.
Good luck!
