### ISSUE TITLE
Is it possible to create `.yarnrc.yaml` and `.yarn/releases/yarn-1.22.19.cjs` in the `build` folder.

### ISSUE THREAD

**Issue by bric3** [siouan/frontend-gradle-plugin#181]
Hi,

I have successfully migrated a yarn 1.x setup to frontend 6.0.0, and I'd like to avoid the creation of files in the project folder, moving much of the stuff outside somewhere in the gradle's `build` folder.

 
- OS: MacOs Monterey
- JDK: OpenJDK 18 (Amazon Corretto)
- Gradle: 7.5-rc-2

Settings in `build.gradle[.kts]` file:
```kotlin
frontend {
    nodeVersion.set("16.15.1")
    yarnEnabled.set(true)
    yarnVersion.set("1.22.19")
    // DONT use the `build` directory if it also the output of the `react-scripts`
    // otherwise it causes 'Error: write EPIPE' because node location is also
    // in the location of the output folder of react-scripts.
    // This projects set up the BUILD_PATH=./build/react-build/ for react-scripts
    nodeInstallDirectory.set(project.layout.buildDirectory.dir("node"))

    assembleScript.set("run build") // "build" script in package.json
}
```

Basically, I'd like to keep sources folder untouched. I have a bare knowledge of yarn, node, etc web technos, please bear with me if I ask stupid questions. Thanks in advance.

----
Project : https://github.com/bric3/excalidraw-jetbrains-plugin

**Comment by bric3** [comment]
Hi @v1nc3n4 

Thanks for the feedback 🙏.

On point 1, I understand the reasoning. On the clean perspective, since `cleanFrontend` is a dependency of the global `clean`, it shouldn't be an issue as it should run first, or I am missing something. And on my part when I clean I definitely want to start from a fresh start, so the `build/` folder is the best fit.

If I could I would even put the `node_module` folder inside the `build/` folder.

Also Gradle can find or install Java toolchains (eg in `~/.gradle/jdks/jdk-9+181/`), maybe that's the way to go ?

On point 2, I mean even the root of the project, creating files here makes the git repo dirty. The `build/` folder is often configured to be ignored. 

Now maybe I'm misunderstanding these files `.yarnrc.yaml` and `.yarn/releases/yarn-1.22.19.cjs`, maybe they should be committed, or not and then the only option is to ignore them ?

**Comment by v1nc3n4** [comment]
Hello!

1. My remark is quite subjective indeed 😄. You may go on with this approach and store the distribution in the `build` directory. Regarding your suggestion to write somes files in the `~/.gradle` directory, and considering [Gradle documentation](https://docs.gradle.org/current/userguide/directory_layout.html#dir:project_root), I would not store the distribution in the project-specific cache, because I don't know what Gradle does exactly. The problem of this documentation is it does not tell the developer where files may be written or not. So, with a defensive approach, I would not mix files of different kinds, and rather write the distribution elsewhere to prevent any conflict. But anyone may configure another location with the `nodeInstallDirectory` property, as you did, and try.

2. To me, that's just a matter of gitignoring another directory/file, which is generally an action done once forever. But you may go on with your idea too.

Your initial question:

> Now maybe I'm misunderstanding these files `.yarnrc.yaml` and `.yarn/releases/yarn-1.22.19.cjs`, maybe they should be committed, or not and then the only option is to ignore them ?

This [page](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) will probably help you!

If these answers are acceptable for you, I will close the issue next days.
Have a nice day!
BR

**Comment by bric3** [comment]
Hi,

Yes thank you for the explanation! By the way you should open a Github discussion section, as my intent was not really to open an issue per se.

----

Side note

> write somes files in the `~/.gradle` directory, and considering [Gradle documentation](https://docs.gradle.org/current/userguide/directory_layout.html#dir:project_root), I would not store the distribution in the project-specific cache

On this the JDK downloaded by gradle itself are stored in `~/.gradle/jdks`, while caches are in `~/.gradle/caches`. That being said I understand the point of not meddling too much with gradle folder.
