### ISSUE TITLE
Return yarnDistributionProvided option

### ISSUE THREAD

**Issue by Gamadril** [siouan/frontend-gradle-plugin#189]
before 6.0.0 there was a very nice option "yarnDistributionProvided" which allowed to use an already existing global yarn version. This is actually the only allowed possibility to use yarn in some environment which work unconnected to internet and use only repositories from intranet.
I can't find the way to make yarn work in offline mode. It seems installYarn always wants to "phone home".

**Comment by v1nc3n4** [comment]
Hi @Gamadril,

Thank you for your message and for using the plugin.
Indeed, property `yarnDistributionProvided` has been removed in version 6.0.0 and I understand it may be surprising. Version 6.0.0 brings support of [Yarn Berry](https://yarnpkg.com/) baseline, and removes support of [Yarn Classic](https://classic.yarnpkg.com) baseline. The plugin will not deal with both baselines in any version, due to the complexity of such implementation. Forcing usage of the Yarn Berry baseline encourages developers to migrate their project. If you can't do that, then you can't upgrade the plugin in version 6.0.0. With your message, I assume you are still using the Yarn Classic baseline in a project (i.e. a Yarn 1.x version). If I'm mistaken, please correct me and sorry for the following details.

Yarn Berry provides access to Yarn v1 (still, but in a totally different way) and Yarn v2+ releases. To do so, Yarn Berry does not rely on a concrete distribution anymore, as opposed to the Classic baseline. Yarn Berry must be seen as a new package manager, not an enhancement. There's no Yarn distribution anymore, that's how the Berry baseline works. Therefore, property `yarnDistributionProvided` and other ones are now irrelevant.

If you succeed in migrating your project to the Berry baseline, then you'll be able to use v6.0.0 of the plugin. If you had a global Yarn distribution somewhere on a disconnected environment, I assume you had also a global Node.js distribution. After migration, you should look at Yarn Berry's documentation to find out how to configure this Node.js distribution, and [what to save in your Git repository](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored).

Hope this helps!
BR

**Comment by Gamadril** [comment]
Hi @v1nc3n4,
thanks for the detailed answer. I'm talking about using preinstalled yarn v3.2.4 Version. Let me explain the situation.
Many workstations with restricted internet access, same situation with Jenkins build server which has no internet access at all. All libs/packages are located on a local nexus server.

To install yarn > classic in such an environment you still need a client with internet access, but only to prepare the package for offline installation later on all other workstations.

Starting point: Local NodeJS version (v16.18.0 in my case)

- Enable corepack
`corepack enable`

- Save yarn 3.2.4 release to local archive
`corepack prepare yarn@3.2.4 -o`

- rename to yarn-3.2.4.tgz and put it on local nexus server

Administration service running on all workstations will execute this in background without user interaction:
```
corepack enable
wget http://nexuss.intern/bin/yarn/yarn-3.2.4.tgz
corepack hydrate yarn-3.2.4.tgz --activate
```

yarn is in PATH, user can start yarn directly
```
$ yarn --version
3.2.4
```

So the gradle plugin should in this case find yarn in PATH and just call it without trying to install it first. I had to go back to 5.3.0, which seems to work in my case.

**Comment by Gamadril** [comment]
I have a workaround for the 6.0.0 version by disabling all node- and yarn-installation tasks

```
installNode.enabled = false
installYarnGlobally.enabled = false
enableYarnBerry.enabled = false
installYarn.enabled = false
```
