### ISSUE TITLE
Task :installFrontend fails

### ISSUE THREAD

**Issue by XhiroYui** [siouan/frontend-gradle-plugin#210]
Hi,

I have a project that uses Spring WebFlux with Vue.js frontend. Trying to make it an all-in-one package as my App is rather small.

What I am trying to do: Run `gradle build` or even `gradle clean`
Expected results: Task runs succesfully
Actual results: `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':installFrontend'.`

**Environment**
 
- OS: [Windows 10 Pro, Mac OS X]
- JDK: [Oracle OpenJDK 20]
- Gradle: [Gradle 8.3]
- Frontend Gradle plugin: [8.0.0 JDK 17]

Settings in `build.gradle` file:

```groovy
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.1.4'
	id 'org.siouan.frontend-jdk17' version '8.0.0'
}

frontend {
	packageJsonDirectory = file("${projectDir}/src/web")
	nodeInstallDirectory = file("${projectDir}/src/web/.node")
	nodeDistributionUrlRoot = "https://nodejs.org/dist/"
	nodeVersion = nodeVersionProp
	assembleScript = "run ${frontendBuild}"
}
```

I'm not sure what other details I missed that's necessary.

[fail.log](https://github.com/siouan/frontend-gradle-plugin/files/12709521/fail.log)

**Comment by XhiroYui** [comment]
[fail.log](https://github.com/siouan/frontend-gradle-plugin/files/12709520/fail.log)

**Comment by v1nc3n4** [comment]
Hi @XhiroYui,

Thank you for using this plugin and your report.
Ideally, can you provide a minimal project to reproduce the issue please? You may also enable verbose mode (property `verboseModeEnabled`) or run gradle with INFO/DEBUG log level (`-i`/`-d` flags) because the log file does not provide helpful information.

You may also start a sample project from [this example](https://github.com/siouan/frontend-gradle-plugin/tree/main/examples/fullstack-war-application) or another one, and move to your configuration step by step to see what causes the failure?

Let me know additional information 😀.
BR

**Comment by XhiroYui** [comment]
Hi again, 

Sorry for some delay as I don't work on this project extremely often. I've managed to make a reproducible sample which I uploaded here. 

https://github.com/XhiroYui/frontendgradleissue

The steps I did to make this is basically just the few below.

1. Spring initializer a WebFlux project
2. Create a new Vite project with `$ npm create vite@latest`
3. Copy the files over to the Spring WebFlux project
4. Set the configuration in the `build.gradle` file
5. Run `gradle clean` or any other command that triggers the :installFrontend task

I've used the latest versions of everything I could find as of time of writing, which may or may not be supported. I'm not sure if the configuration is correct unfortunately as nothing I did made the task to not fail.

**Comment by v1nc3n4** [comment]
Hi @XhiroYui,

Thank you for the sample project. I think the problem is related to Node.js / Corepack / NPM. I can't explain why task `installFrontend` fails precisely. But the task simply runs command `npm install` in the relevant working directory (with `-i` flag, you can see the exact environment used). This command fails without printing a message, and I don't think it is caused by the plugin itself.

I tried with Node.js 18.18.0, and the issue seems to have been fixed whatever it was (Node.js [changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.18.0) shows multiple Corepack update at least). While digging into the problem, I also faced many errors with the download of Node.js distribution. It seems the Node.js server is a bit unstable. A year ago, I remember having some strange issues also with Node.js distributions being for an unknown reason unstable when using Corepack and NPM (see issue #183), and some months later the exact same distribution working smoothly. I never add some news from Node.js team about that despite [this issue](https://github.com/nodejs/corepack/issues/178).

Anyway, I hope you can upgrade to Node.js 18.18.0 and check if everything works fine. Let me know the results of course! 🙂
BR

**Comment by XhiroYui** [comment]
Hi,

Didn't realise that NodeJs actually released 18.18.0 not long after I made the addition of this plugin, thus why I mentioned it was latest in the post above.

**Changing to 18.18.0 works**. I can't say I'm familiar with the inner workings of NPM so most of the info shared kind of went over my head but thanks for sharing. Since this seems like not a fault of the plugin, will close this issue then. Much appreciated for the prompt responses.

Regards~

**Comment by v1nc3n4** [comment]
You're welcome!
FYI, I made some additional tests with different combinations of Node.js / npm because I didn't understand why [this example](https://github.com/siouan/frontend-gradle-plugin/tree/main/examples/npm-application) was working with Node.js 18.17.1 and your project not. Finally, here are some interesting results:

| Node.js | npm | Result |
| - | - | - |
| 18.17.1 | 9.6.7 | ✔️ |
| 18.17.1 | 9.7.0 | ✖️ |
| 18.17.1 | 9.7.1 | ✖️ |
| 18.17.1 | 9.7.2 | ✖️ |
| 18.17.1 | 9.8.0 | ✖️ |
| 18.17.1 | 10.0.0 | ✖️ |
| 18.17.1 | 10.1.0 | ✖️ |
| 18.18.0 | 9.6.7 | ✔️ |
| 18.18.0 | 9.7.0 | ✔️ |
| 18.18.0 | 9.7.1 | ✔️ |
| 18.18.0 | 9.7.2 | ✔️ |
| 18.18.0 | 9.8.0 | ✔️ |
| 18.18.0 | 10.0.0 | ✔️ |
| 18.18.0 | 10.1.0 | ✔️ |

**Comment by v1nc3n4** [comment]
For reference: it seems the problem is tighly coupled with Corepack 0.18.0, which is provided by default in Node.js 18.17.1. Upgrading to Corepack >= 0.18.1 allows to use any npm release with Node.js 18.17.1. This can be done with command `npm install -g corepack`. When using the plugin, this could be done with an additional Gradle task:

With Kotlin language:
```kotlin
import org.siouan.frontendgradleplugin.infrastructure.gradle.RunNpm
tasks.register<RunNpm>("updateCorepack") {
    dependsOn(tasks.named("installNode"))
    script.set("install -g corepack")
}

tasks.named("resolvePackageManager").dependsOn(tasks.named("updateCorepack"))
```

With Groovy language:
```groovy
import org.siouan.frontendgradleplugin.infrastructure.gradle.RunNpm
tasks.register('updateCorepack', RunNpm) {
    dependsOn tasks.named('installNode')
    script = 'install -g corepack'
}

tasks.named('resolvePackageManager') {
    dependsOn tasks.named('updateCorepack')
}
```
Here are some additional tests:

| Node.js | Corepack | npm | Result |
| - | - | - | - |
| 18.17.1 | 0.18.0 | 9.6.7 | ✔️ |
| 18.17.1 | 0.18.0 | 9.7.0 | ✖️ |
| 18.17.1 | 0.18.1 | 9.6.7 | ✔️ |
| 18.17.1 | 0.18.1 | 9.7.0 | ✔️ |
