### ISSUE TITLE
assembleFrontend executed without up-to-date check

### ISSUE THREAD

**Issue by sergeykad** [siouan/frontend-gradle-plugin#213]
---

Hi,

I am more or less copied the example [here](https://github.com/siouan/frontend-gradle-plugin/blob/main/examples/yarn-application-with-node-modules-linker/build.gradle.kts) into my project and noticed that `assembleFrontend` task is always executed regarding if anything changes from the last build. To rephrase it, if I run `build` command twice it will run assembleFrontend twice as well.

What I am trying to do: validate build results caching and up-to-date checks
Expected results: tasks are executed only if the results are outdated
Actual results: `assembleFrontend` is always executed.

**Environment**
 
- OS: Ubuntu 22.04.1
- JDK: Adoptium Temurin JDK 17 64 bits
- Gradle: 8.4
- Frontend Gradle plugin:  8.0.0 JDK 17

Settings in `build.gradle` file:
```groovy
frontend {
    packageJsonDirectory = file("${project.projectDir}/maintenance")
    nodeVersion = '20.9.0'
    nodeInstallDirectory = file("${projectDir}/.gradle/node")
    assembleScript = "run build"
    verboseModeEnabled.set(true)
}
```

**Comment by v1nc3n4** [comment]
Hi @sergeykad,

Thank you for using the plugin.
Task `assembleFrontend` does not provide "up-to-date" checks by default, as explained in the official documentation [here](https://siouan.github.io/frontend-gradle-plugin/node-corepack-npm-pnpm-yarn-tasks#assembleFrontend). To do that, you must configure inputs and outputs by yourself, because you are the only one who can tell what they are in your project (source files, media, config files, etc.).

Moreover, I don't recommend installing the Node.js distribution in Gradle's [project-specific cache directory (`.gradle`)](https://docs.gradle.org/current/userguide/directory_layout.html#dir:project_root:cache_cleanup), because it is entirely managed by Gradle for its internal processing, and there's a periodic cleanup that may remove the distribution unexpectedly. I suggest you use the default value or another directory of your choice.

I hope this helps 😊.
BR

**Comment by sergeykad** [comment]
Thanks for the prompt response. I must have missed this part of the documentation. I will change it accordingly.
