### ISSUE TITLE
AccessDeniedException when exploding node distribution from download folder, to specified node directory

### ISSUE THREAD

**Issue by rolaca11** [Siouan/frontend-gradle-plugin#62]
Hi,

**Describe the bug**
During the `installNode` task, the application downloads and extracts the given nodejs version. When it tries to copy it to the given `node` folder (even the default), an exception is get thrown:

```
Caused by: java.nio.file.AccessDeniedException: ***sample-gwt-application\*-gwt\build\node\node-v12.13.0-win-x64\node_modules -> ***sample-gwt-application\*-gwt\build\node\node_modules
	at org.siouan.frontendgradleplugin.core.Utils.lambda$moveFiles$3(Utils.java:203)
	... 177 more
```

**Expected behavior**
The exploding runs seemlessly and the downloaded node version appears in the `node` directory.

**To Reproduce**
1. Put these settings in `build.gradle`: 
```
frontend {
    nodeVersion: '12.13.0'
}
```
2. Execute the Gradle task `installNode`
3. See error/issue

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - JDK: Oarcle JDK 1.8.0_221
 - Gradle: 5.6.1
 - Frontend Gradle plugin: 1.2.1

**Additional context**
The script has been tried with GitLab runner and command prompt, both fail on the above mentioned OS. Runs without problem on Windows 10.

**Comment by vboriesazeau** [comment]
Hi,
Thank you for your feedback. I'm not sure right now what causes this issue. I can only think about a relation with Windows Server 2016 or an issue that prevents files from being moved, if one is still opened by a process for example, or if the moving logic in the plugin is bad.
In README file, Windows is announced to be supported, but I realize now it is not enough accurate, since the test suite was executed on Windows 10 Home only.

To go further, I found a way to build the plugin under Windows Server 2016 release 1803 with Travis, even if such configuration is at an early stage in Travis. Then the plugin will be built and tested automatically on Windows Server too from release 1.3.0.
However, no error appears during such build, and I could not reproduce the issue you encountered.

Finally, I decided to change the moving logic that is highlighted by the issue. If you are able to test again your case with branch 1.3, I'll be happy to read the results. Otherwise, once next release is published, please upgrade your version, and tell me here if the issue was fixed.

Thank you for your help!
Vincent

**Comment by rolaca11** [comment]
Thank you for answering, since then I seem to have found a fix/workaround to the issue.

I forked the repo on the company git repo and did the fix there, will create a github pr as well, if I don't forget.

The fix basically is that the `Files.move()` method is only used to move files and not directories. It means, that at the point suggested by the exception stack trace I check if the `childPath` is a directory or not. If it is, then I recursively call the `Utils.moveFiles()` method again, to the given child directory. If the `childPath` represents a file, I just call the `Files.move` method as it is in the current version.

**Comment by vboriesazeau** [comment]
Thanks for your answer!
In fact, I dug into the `Files.move` method too, and it deals correctly with directories recursively, _as long as they are in the same volume_: it behaves like a `rename` on the root directory, and it works like a charm. Just moving the root directory is enough to move the entire file tree. That's what the fix does, and it replaces a weak implementation based on `Files.list` method with a single line.
The `Files.list` method does not guarantee to reflect any changes in the file system, and the order doesn't seem to be predictable. I highly suspect the plugin was attempting to move a file that didn't exist anymore, since its parent directory (and itself so) had been moved a loop before.
Unless Gradle temporary directory (in `$buildDir/tmp/installNode` and the install directory chosen in your build configuration are not in the same volume, I think it should work now with this fix. However, I'm sure of nothing because I could not reproduce the issue. So let me know your results :)!
Again, thanks for your help!

**Comment by rolaca11** [comment]
> it behaves like a rename on the root directory, and it works like a charm

Based on my research, this is exactly the cause of the root problem in this issue. Once I get back to work, I'll check out your fix on our server and give feedback.
