### ISSUE TITLE
Mismatch in documentation and actual implementation with nodeInstallDirectory

### ISSUE THREAD

**Issue by TapaiBalazs** [Siouan/frontend-gradle-plugin#70]
Hi,

**Describe the bug**
We are using the plugin to build our projects. The documentation states that if we want to change the install directory of node we need to add the following into the config:

```
frontend {
  nodeInstallDirectory = "${projectDir}/anotherdir/node"
}
```

But using that causes an error: `Cannot set the value of extension 'frontend' property 'nodeInstallDirectory' of type java.io.File using an instance of type java.lang.GString`

After checking out your source code we noticed that that argument expects a `File`  type, and using `new File()` solves our problem.

**Expected behavior**
Please update the documentation:

```
    // [OPTIONAL] Install directory where the distribution archive shall be exploded.
    nodeInstallDirectory = new File("${projectDir}/node")

```

**Additional context**
Thank you for the plugin it is awesome! :)

**Comment by vboriesazeau** [comment]
Hi @TapaiBalazs 
Thank you for your feedback!
You are certainly right. For the moment, it's a bit weird to me, since I don't understand why some projects work fine with the syntax introduced in the docs, and why some don't with the error you mentioned.
Anyhow, I'll use the explicit Groovy syntax in the next release to improve clarity.
Thanks again for your help!
Vincent

**Comment by TapaiBalazs** [comment]
We use Gradle 6.1.1 if that helps to investigate.
