### ISSUE TITLE
Use provided Node/Yarn distributions

### ISSUE THREAD

**Issue by vboriesazeau** [Siouan/frontend-gradle-plugin#86]
**Description**

Depending on the context, a shared Node/Yarn distribution may be used on a workstation for different projects: independent Gradle projects, Maven projects, or any other application. The distribution typically may be located anywhere on the workstation. Such environment would take advantage of a configuration option in the plugin to use the preinstall distribution. Consequently:

- The `installNode` task and/or the `installYarn` task would be skipped if executed.
- The `nodeVersion` property would become optional.
- The `nodeInstallDirectory` property and the `yarnInstallDirectory` property would point to the shared distribution location.
- The distribution would not be managed by the plugin anymore: the plugin will neither download the distribution nor check if the distribution has been 'touched'.

Settings in the `build.gradle` file could be as below:
```groovy
frontend {
    nodeDistributionProvided = true
    nodeInstallDirectory = file('/opt/node/node-v12.16.2')
    yarnDistributionProvided = true
    yarnInstallDirectory = file('/opt/yarn/yarn-v1.22.4')
}
```

**Comment by ludik0** [comment]
Am I just missing an option or is it not possible to call the node distribution that is available in the path ? Why do I have to specify a installation directory ?

I get the error:
A problem was found with the configuration of task ':wr-client-ng:installFrontend'.
> Directory '<path to project/node>' specified for property 'nodeInstallDirectory' does not exist.

Thank you for your help :)

**Comment by v1nc3n4** [comment]
Hi @ludik0,

These are interesting questions.

> Am I just missing an option or is it not possible to call the node distribution that is available in the path ?

Indeed, this is the expected behavior \[[1][installnode-task]\], and as you have already noticed with the error, the install directory must be explicitly set.

> Why do I have to specify a installation directory ?

Relying on the `PATH` variable was not an identified use case, although it seems relevant. It also seems it would work flawlessly with actual distributions of Node.js under Unix-like O/S and Windows O/S.
**However**, there's no guarantee the `node` executable don't require a file in the distribution that is not accessible with the `PATH` environment variable. Why do distributions contain many other files than just executables? A Node.js contributor maybe could answer to this question. As long as we should not have to know how distribution's content is used, dealing with the executable path only could potentially be a problem. That's why the plugin deals with installation directories instead of executable paths, to ensure it can provide the context executables may expect.

Now, if you want to deal with it until an improvement is available, I would suggest the following steps based on [this section][use-nodejsnpmnpxyarn-apart-from-gradle] of the documentation:

- Define a `NODEJS_HOME` environment variable pointing to the install directory of the distribution.
- In the `PATH` environment variable, use an executable path based on the `NODEJS_HOME` environment variable.
- Configure the plugin as below:

```groovy
frontend {
    nodeInstallDirectory = file(System.getEnv('NODEJS_HOME'))
}
```

I think there's a relevant improvement to be implemented in the plugin, that's why I will create a dedicated feature request for it.

Thank you for your interest!
BR,
Vincent

[installnode-task]: <https://github.com/siouan/frontend-gradle-plugin/tree/2.1/README.md#installnode---install-nodejs> (Install Node.js)
[use-nodejsnpmnpxyarn-apart-from-gradle]: <https://github.com/siouan/frontend-gradle-plugin/tree/2.1/README.md#use-nodejsnpmnpxyarn-apart-from-gradle> (Use Node.js/npm/npx/Yarn apart from gradle)
